name: Generate a build from main and push to gh-pages

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and push to gh-pages
    steps:
      - name: git-checkout
        uses: actions/checkout@v3.3.0

      - name: install node modules
        run: npm i

      - name: test app
        run: npm run test