name: Run project test files

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: run test files
    steps:
      - name: git-checkout
        uses: actions/checkout@v3.3.0

      - name: go to client code
        run: cd ./client

      - name: install node modules
        run: npm i

      - name: run client test files
        run: npm run test
