name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: run test files
    steps:
      - name: git-checkout
        uses: actions/checkout@v3.3.0

      - name: install and run client test files
        working-directory: ./client
        run: |
          npm i
          npm run test
